spring:
  liquibase:
    enabled: true

  datasource:
    url: jdbc:postgresql:publications
    username: springuser
    password: 123

  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  servlet:
    multipart:
      enabled: true
      location: ${java.io.tmpdir}
      max-file-size: 1MB

management:
  endpoints:
    web:
      exposure:
        include: health,info,logfile

  endpoint:
    logfile:
      enabled: true

    health:
      show-details: when_authorized
      show-components: when_authorized
      roles: ADMIN

logging:
  file:
    path: logs