spring:
  liquibase:
    enabled: true

  datasource:
    url: jdbc:postgresql:publications
    username: springuser
    password: 123

  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  servlet:
    multipart:
      enabled: true
      location: ${java.io.tmpdir}